### PR TITLE
update simple-sonoff-server version

### PR DESCRIPTION
**Pull request by mdopp**
Changes for this project have been implemented into the master-branch of simple-sonoff-server. And also a few bugs were solved (i.E. "close" does now close all connections). Additionally, the http server was moved to the main module, as it should not be necessary when node-red is used.

### CODE REVIEW

**Comment by mdopp** [comment]
Before I forget => Can you please also update the npm packages?

btw: I really like what you did here! Was exactly what I was hoping to accomplish some day :)

**Comment by Tex627** [comment]
Newbie to all this. Once i have my server set-up and i join the sonoff to my server. How  or which app do you use to control the sonoff switch?

**Comment by mdopp** [comment]
@text627: a pull request is about changing the code. Please do not mis use it as a forum. Maybe you can raise an issue with your question, or write the maintainer an email (package.json contains it).
But to answer your question: this is a node-red plugin so you need that installed, and can make use of it's functionality. But it's not an app

**Comment by saryn** [comment]
There is no need to update dependency version (simple-sonof-server) as it is fixed to most update major version. 
See e.g. https://stackoverflow.com/a/22345808

Please follow-up semantic versioning when updating your code.
Since it is published in npm, you could break some else's code.
See https://semver.org/

Thanks for fixing and optimalization (no need to run HTTP server).
I will update it in npm.

**Pull request closed without merging**
